apiVersion: v1
kind: Secret
metadata:
  name: fediseer-secrets
  namespace: lemmy
stringData:
  # This is your instance. ie, lemmyonline.com
  FEDISEER_INSTANCE: lemmy.yourdomain.com
  # Administrative username, for your instance
  FEDISEER_USERNAME: your_admin_username
  # Password for above user account.
  FEDISEER_PASSWORD: "your_admin_password"
